<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

use App\Http\Controllers\adminController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-27 at 06:59:41.
 */
class adminControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var adminController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new adminController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


//    /**
//     * @covers App\Http\Controllers\adminController::main
//     * @todo   Implement testMain().
//     */
//    public function testMain() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers App\Http\Controllers\adminController::login
//     * @todo   Implement testLogin().
//     */
//    public function testLogin() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers App\Http\Controllers\adminController::logout
//     * @todo   Implement testLogout().
//     */
//    public function testLogout() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers App\Http\Controllers\adminController::getControl
//     * @todo   Implement testGetControl().
//     */
//    public function testGetControl() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers App\Http\Controllers\adminController::formatearNumero
     * @todo   Implement testFormatearNumero().
     * @covers Implement testFormatearNumero().
     */
    public function testFormatearNumero() {
        // 20161
        $numero = $this->object->formatearNumero('20161', 3);
        
        //var_dump($numero);die;
        
        // Remove the following lines when you implement this test.
        $this->assertEquals($numero, '1/2016');
        
        // 2016A1
        $numero = $this->object->formatearNumero('2016A1', 3);
        
        //var_dump($numero);die;
        
        // Remove the following lines when you implement this test.
        $this->assertEquals($numero, 'A1/2016');
        
    }

//    /**
//     * @covers App\Http\Controllers\adminController::formatearNumeroOrdenar
//     * @todo   Implement testFormatearNumeroOrdenar().
//     */
//    public function testFormatearNumeroOrdenar() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers App\Http\Controllers\adminController::numeroNuevo
//     * @todo   Implement testNumeroNuevo().
//     */
//    public function testNumeroNuevo() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers App\Http\Controllers\adminController::numeroNuevoAbono
//     * @todo   Implement testNumeroNuevoAbono().
//     */
//    public function testNumeroNuevoAbono() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers App\Http\Controllers\adminController::desFormatearNumero
//     * @todo   Implement testDesFormatearNumero().
//     */
//    public function testDesFormatearNumero() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers App\Http\Controllers\adminController::formateaNumeroContabilidad
//     * @todo   Implement testFormateaNumeroContabilidad().
//     */
//    public function testFormateaNumeroContabilidad() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers App\Http\Controllers\adminController::editarCampoNumero
//     * @todo   Implement testEditarCampoNumero().
//     */
//    public function testEditarCampoNumero() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

}
